### PR TITLE
Making Approle Path an Environment variable to cater for Vault 

### PR DESCRIPTION
**Pull request by kenrickles**
Please see issue: 
https://github.com/ConsenSys/quorum-account-plugin-hashicorp-vault/issues/21

### CODE REVIEW

**Review by baptiste-b-pegasys — APPROVED** [review]

**Comment by KenrickTanPartior** [comment]
Hi @baptiste-b-pegasys, will this change be merged?

**Comment by baptiste-b-pegasys** [comment]
hello, the main issue is to get the github action all green. We tried to upgrade to go 1.18, but it's failing. Another project had been updated since, and it's not possible to get the itests green.

I will take a look again where we are from now.

**Comment by KenrickTanPartior** [comment]
Sorry to keep bothering @baptiste-b-pegasys but any updates on this?

**Comment by baptiste-b-pegasys** [comment]
not able to pass the make itest for the moment

**Review by antonydenyer — CHANGES_REQUESTED** [review]
@kenrickles getting there finally! Can you fix up the build and we should be good

**Comment by kenrickles** [comment]
> @kenrickles getting there finally! Can you fix up the build and we should be good

We should be good to go. But I tested locally. So fingers crossed 😅

**Comment by kenrickles** [comment]
Seems like the tests on signer isn't working. I'll give it a go tomorrow.

**Pull request merged**
